apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 3
  selector:
    app: myjavaapp
    version: 2.6.1
  template:
    metadata:
      labels:
        app: myjavaapp
        version: 2.6.1
    spec:
      containers:
        - name: javaappcontainer
          image: maha4iac/myonlineboking:1
          ports:
            - containerPort: 80
