apiVersion: v1
kind: ReplicationController
metadata:
  name: MYnginxRC
spec:
  replicas: 10
  selector:
    app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
        - name: nginxcontainer
          image: nginx
          ports:
            - containerPort: 80
